version: "3.8"
services:
  frontend:
    build:
      context: ./ResumeBuilderAngular
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    environment:
      - NODE_ENV=production

  backend:
    build:
      context: ./ResumeBuilderBackend
      dockerfile: Dockerfile
    ports:
      - "4292:4292"
    environment:
      - NODE_ENV=production
